-- NOTICE: Functions have been moved to separate migration files
-- Migration: 20250711095000_create_messaging_rpc.sql
--
-- The RPC functions originally defined in this file have been moved to separate 
-- migration files to resolve syntax issues and parameter name conflicts:
--
-- 1. get_conversation_messages -> 20250711120000_create_message_rpc.sql
--    - Fixed parameter name conflicts between function parameters and column names
--    - Renamed columns to avoid ambiguity
--
-- 2. get_user_conversations -> 20250711121000_create_conversations_rpc.sql
--    - Fixed syntax issues with CTE aliases
--    - Improved naming for better readability
--
-- This separation allows for easier maintenance and troubleshooting of each function.
